lab-app:
  auth:
    path-whitelist:
      - /api/swagger-ui.html
      - /api/v2/api-docs
      - /api/swagger-resources/**
      - /api/webjars/**
      - /api/v1/verify-code/**
      - /api/v1/check-verify-code/**
      - /api/v1/login
      - /api/v1/register
      - /api/v1/sign-up
    enabled: true
    mocked-admin:
      id: 100100
      username: mocked.admin
      name: admin
      nickname: yoon
      phone: 13012345678
      email: mock@me.com
      type: 1
      refId: 100100
    mocked-teacher:
      id: 100101
      username: mocked.teacher
      name: teacher
      nickname: yoon
      phone: 13012345678
      email: mock@me.com
      type: 2
      refId: 100101
  login:
    email-mode-enabled: true
  registration:
    admin-whitelist:
      - ycourlee@qq.com
    admin:
      default-role-id:
        - 1
    teacher:
      default-role-id:
        - 2

logging:
  level:
    root: info

spring:
  mail:
    host: @lab-booking.noreply.email.smtp.host@
    port: @lab-booking.noreply.email.smtp.port@
    username: @lab-booking.noreply.email.smtp.username@
    password: @lab-booking.noreply.email.smtp.password@