server:
  port: 8000
  servlet:
    context-path: /api


spring:
  application:
    name: laboratory booking management system
  redis:
    host: localhost
    database: 0
    port: 6380

logging:
  level: info
lab:
  app:
    authentication:
      enabled: true
    url:
      whitelist:
        -/api